services:
  - mysql

environment:
  matrix:
    - PYTHON: "C:\\Miniconda3-x64"
      PYTHON_VERSION: "3.7"
      PYTHON_ARCH: "64"
      platform: x64
      STANDALONE: "FALSE"
      CONDA_PY: "37"
      CONDA_BUILD: "TRUE"
      SPLIT_RUN: "FALSE"
#  PMG_MAPI_KEY:
#    secure: XIbk1W27nucVUHTVpIL2B+FodL9w2Efyw5PqTdnfbHg=
  PYPIPWD:
    secure: QPpXonUAeLJ8p3f936jh7g==
install:
  # Add the paths
  - 'set PATH=%PYTHON%;%PYTHON%\Library\bin;%PYTHON%\Scripts;%PATH%'
  - 'set MPLBACKEND=Agg'
  - 'conda config --system --add channels conda-forge'
  - 'conda create --yes -q -n test-environment python=3.7 numpy scipy matplotlib cython pandas networkx pytest pip cmake h5py python-igraph phonopy'
  - 'conda activate test-environment'
  # Install the build dependencies of the project via conda and pip
  - 'pip install -r requirements.txt'
  - 'pip install pybtex tqdm'
  # Run develop to install in dev mode and build C extension.
  - "pip install --quiet -e ."

build: false

test_script:
  - 'conda activate test-environment'
  - "pytest --failed-first --exitfirst --ignore=pymatgen/ext/tests/test_matproj.py --ignore=pymatgen/analysis/tests/test_pourbaix_diagram.py --ignore=pymatgen/tests/test_init.py --ignore-glob='pymatgen/analysis/defects/tests/test_*.py' pymatgen"

notifications:
  - provider: Email
    to:
      - shyuep@gmail.com
    on_build_success: false
    on_build_failure: true
    on_build_status_changed: true

deploy_script:
   - IF "%APPVEYOR_REPO_BRANCH%" == "stable" (python setup.py sdist bdist_wheel)
   - IF "%APPVEYOR_REPO_BRANCH%" == "stable" (twine upload --username Shyue.Ping.Ong --password %PYPIPWD% dist/*.whl)
