name: Build wheels for PyPI

on:
  push:
    branches:
      - master

jobs:
  build_wheels:
    name: Build wheel on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04, windows-latest, macos-latest]

    steps:
    - uses: actions/checkout@v1

    - uses: actions/setup-python@v1
      name: Install Python
      with:
        python-version: '3.8'

    - name: Install cibuildwheel
      run: |
        python -m pip install cibuildwheel==1.3.0
    - name: Build wheel
      env:
        # Skip Python 2.7 and Python 3.5 and PyPy wheels
        CIBW_SKIP: cp2* cp35-* pp*
      run: |
        python -m cibuildwheel --output-dir wheelhouse
    - uses: actions/upload-artifact@v1
      with:
        name: wheels
        path: ./wheelhouse
